### ISSUE TITLE
Internal parsing error: sys-freeMem: number too large to fit in target type

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/esdb-tui#6]
![image](https://user-images.githubusercontent.com/13871941/177585823-773b193a-d74a-485e-8cf7-adac440bd081.png)

**Comment by StevenBlair123** [comment]
My PC has 64gig ram (and currently 33gb free)

**Comment by YoEight** [comment]
Thanks for testing @StevenBlair123 !

Currently, that value is stored in a signed 64bits integer. I'll move it to unsigned.

**Comment by YoEight** [comment]
<img width="852" alt="snip" src="https://user-images.githubusercontent.com/144545/177908480-d069513c-c769-49a2-8766-9fd5a8e6fc94.png">

While I never experienced that issue on Linux (my rig also got 64GB), I have a patch that seems to not panic on Windows either.

**Comment by YoEight** [comment]
Here is the release candidate of that patch (it also includes the patch about the window's header showing the full connection string). If you got some spare, I would like to have your feedback on it, please:

https://github.com/EventStore/esdb-tui/releases/tag/0.22.7-alpha

**Comment by StevenBlair123** [comment]
Looks good!.
Dashboard is also now displaying information (I assumed it was related)

**Comment by YoEight** [comment]
Fixed
